default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doctor_api_development

test:
  <<: *default
  database: doctor_api_test

production:
  <<: *default
  database: doctor_api_production
  username: doctor_api
  password: <%= ENV['DOCTOR_API_DATABASE_PASSWORD'] %>
